TravelMate-Ajou-Univ/Backend

- .github/workflows/cicd.yml
> fix: yml script

- src/bookmark/bookmark.service.ts
- src/user/user.module.ts
> feat: prisma Service 수정

- src/main.ts
Cors origin 추가
- 특이 사항 1
- 특이 사항 2
> hotfix: local에서 Frontend API테스트를 위한 cors origin 추가

- src/auth/auth.controller.ts
- src/auth/auth.service.ts
> Feat : Google sign in & refresh jwt

- prisma/schema.prisma
- src/bookmarkCollection/bookmark-collection.service.ts
- src/bookmarkCollection/dtos/req/FetchMyBookmarkCollections.dto.ts
- src/bookmarkCollection/dtos/req/update-bookmark-collection.dto.ts
- src/common/decorators/api-ok-response-paginated.decorator.ts
- src/common/paginate/offset-paginated.dto.ts
- src/common/paginate/page-meta.dto.ts
- src/common/paginate/paginate-query.dto.ts
- src/location/dtos/location.dto.ts
- src/location/entities/location.entity.ts
- src/main.ts
- src/user/user.controller.ts
> [master] 내 북마크 컬렉션 조회시 페이지네이션 적용함

- prisma/migrations/20231030091704_change_latitude_longtude_decimal_scope/migration.sql
- prisma/schema.prisma
- src/bookmarkCollection/bookmark-collection.service.ts
- src/bookmarkCollection/dtos/req/FetchMyBookmarkCollections.dto.ts
- src/location/dtos/location.dto.ts
- src/location/entities/location.entity.ts
> feat: 위도 경도 좌표

- src/user/user.controller.ts
> feat: DTO 네이밍 수정

- prisma/schema.prisma
- src/bookmark/bookmark.service.ts
- src/bookmarkCollection/bookmark-collection.service.ts
- src/bookmarkCollection/dtos/req/create-bookmark-collection.dto.ts
- src/bookmarkCollection/dtos/req/fetch-my-bookmark-collections.dto.ts
- src/user/user.controller.ts
- src/user/user.service.ts
> [master[ hotfix: JwtGuard 적용 및 Enum ALL 추가

- package-lock.json
- package.json
- prisma/migrations/20231030103328_add_article_models/migration.sql
- prisma/migrations/20231102074441_add_attachments/migration.sql
- prisma/migrations/20231102080345_profile/migration.sql
- prisma/migrations/20231102080909_fix_profile/migration.sql
- prisma/schema.prisma
- src/app.module.ts
- src/article/article.controller.ts
- src/article/article.module.ts
- src/article/article.service.ts
- src/article/dtos/create-article.dto.ts
- src/attachment/attachment.controller.ts
- src/attachment/attachment.module.ts
- src/attachment/attachment.service.ts
- src/config/aws.config.ts
- src/prisma.service.ts
- src/s3/dtos/get-presigned-post.dto.ts
- src/s3/s3.controller.ts
- src/s3/s3.module.ts
- src/s3/s3.service.ts
- tsconfig.json
> upload image

- src/main.ts
> [master] hotfix: addBearerAuth설정 추가

- prisma/migrations/20231106091237_article_version_user/migration.sql
- prisma/schema.prisma
- src/app.module.ts
- src/article/article.controller.ts
- src/article/article.module.ts
- src/article/article.service.ts
> Feat : Create article

- src/user/entities/user.entity.ts
- src/user/user.controller.ts
> [master] feat: 채팅서버에 유저정보를 제공하기 위한 api

- prisma/migrations/20231110090718_alter_content_type_to_text/migration.sql
- prisma/schema.prisma
> [master] hotfix: 게시글 내용 도메인 수정

- src/bookmarkCollection/bookmark-collection.service.ts
- src/bookmarkCollection/dtos/req/fetch-my-bookmark-collections.dto.ts
- src/common/dtos/offset-pagination.dto.ts
- src/user/user.controller.ts
> [master] Feat/bookmark collection

- prisma/migrations/20231113100632_add_deleted_at_to_article_table/migration.sql
- prisma/schema.prisma
- src/article/article.controller.ts
- src/article/article.service.ts
> [master] feat: 게시글 soft delete

- prisma/migrations/20231113104232_add_unique_index/migration.sql
- prisma/schema.prisma
- src/article/article.controller.ts
- src/article/article.service.ts
- src/friend/friend.service.ts
- src/user/user.controller.ts
> [master] feat: 게시글 즐겨찾기 관련 API 개발

- src/article/article.service.ts
- src/article/dtos/get-articles.dto.ts
> period toggle

- prisma/migrations/20231114085726_add_place_id_column_to_location_table/migration.sql
- prisma/schema.prisma
- src/article/article.service.ts
- src/bookmarkCollection/bookmark-collection.service.ts
- src/bookmarkCollection/dtos/req/update-bookmark-collection.dto.ts
- src/location/entities/location.entity.ts
> [master] Location테이블에 placeId 추가

- src/friend/friend.service.ts
> [master] 내 친구목록 조회 API hotfix

- prisma/migrations/20231116092602_accept_decline/migration.sql
- prisma/migrations/20231116092724_type/migration.sql
- prisma/schema.prisma
- src/article/article.controller.ts
- src/article/article.service.ts
> Feat : accept and decline requests

- src/user/user.controller.ts
- src/user/user.service.ts
> [master] feat: 유저 정보를 쿼리스트링으로 받고 그 유저들의 정보를 제공하는 API

- src/user/user.controller.ts
> [master] feat: endpoint 수정

- src/user/user.controller.ts
- [] 기능개발(Feature)
- 특이 사항 1
- 특이 사항 2
> [master] user 정보 제공하는 controller 수정

- prisma/migrations/20231121131037_set_nickname_unique/migration.sql
- prisma/migrations/20231121131542_alter_location_unique_key/migration.sql
- prisma/migrations/20231121141727_remove_deleted_at/migration.sql
- prisma/schema.prisma
- src/app.module.ts
- src/article/article.service.ts
- src/auth/auth.service.ts
- src/bookmark/bookmark.controller.ts
- src/bookmark/bookmark.module.ts
- src/bookmark/bookmark.service.ts
- src/bookmarkCollection/bookmark-collection.service.ts
- src/friend/friend.service.ts
- src/user/user.controller.ts
- src/user/user.service.ts
> [master] Fix/bug

- src/bookmark/bookmark.service.ts
> [master] create bookmark 수정

- src/friend/friend.service.ts
> [master] validation 추가

- src/main.ts
> [master] request entity too large error 수정

- src/chatBookmarkCollection/chat-bookmark-collection.controller.ts
- src/chatBookmarkCollection/chat-bookmark-collection.service.ts
> 채팅방 북마크 컬렉션 작업

- src/article/article.service.ts
> [master] location 정보도 보내주도록 수정

- src/article/article.controller.ts
- src/article/article.service.ts
> [master] Fix/get articles

- prisma/migrations/20231205021716_create_user_report_log_table/migration.sql
- prisma/migrations/20231205023537_create_user_level_column/migration.sql
- prisma/schema.prisma
- src/admin/admin.controller.ts
- src/admin/admin.module.ts
- src/admin/admin.service.ts
- src/admin/dtos/fetch-user-report-logs.dto.ts
- src/app.module.ts
- src/auth/auth.service.ts
- src/common/guards/admin.guard.ts
- src/user/dtos/user.dto.ts
- src/user/entities/user.entity.ts
- src/user/user.service.ts
- src/userReportLog/dtos/create-user-report-log.dto.ts
- src/userReportLog/user-report-log.controller.ts
- src/userReportLog/user-report-log.module.ts
- src/userReportLog/user-report-log.service.ts
> [master] 다른 유저를 신고할 수 있는 기능 및 관리자가 유저 신고 목록을 조회할 수 있는 API 및 Admin Guard 적용

- prisma/schema.prisma
- src/admin/admin.controller.ts
- src/admin/admin.module.ts
- src/admin/admin.service.ts
- src/app.module.ts
- src/article/article.controller.ts
- src/article/article.module.ts
- src/article/article.service.ts
- src/articleReportLog/article-report-log.module.ts
- src/articleReportLog/article-report-log.service.ts
- src/articleReportLog/dtos/report-article.dto.ts
- src/auth/auth.service.ts
- src/user/dtos/user.dto.ts
- src/user/entities/user.entity.ts
> [master] Feat/admin api

- prisma/migrations/20231205045628_unique_key/migration.sql
> [master] migration file

- src/auth/auth.service.ts
> reaosn default 처리

- prisma/schema.prisma
- src/auth/auth.service.ts
> [master] 토큰 재발급시에 유저가 밴당했는지 확인

- prisma/schema.prisma
- src/admin/admin.controller.ts
- src/articleReportLog/article-report-log.service.ts
- src/userReportLog/user-report-log.service.ts
> [master] 신고받은 사람, 신고한사람, 게시글정보도 같이 가져오도록 수정

- src/s3/dtos/get-presigned-post.dto.ts
> EPresignedPostType 수정

- prisma/schema.prisma
- src/s3/s3.service.ts
> presigned url 채팅 이미지 타입 추가

- prisma/migrations/20231205141052_attachment_type_enum_update/migration.sql
> attachment type 수정

- src/s3/s3.service.ts
> upload success service type 수정

- src/bookmarkCollection/bookmark-collection.service.ts
- src/user/user.controller.ts
> [master] bookmark collection 수정 및 삭제시 로그인한 사람이 컬렉션 소유자인지 확인

- src/bookmarkCollection/bookmark-collection.service.spec.ts
- src/bookmarkCollection/bookmark-collection.service.ts
- src/bookmarkCollection/data/bookmark-collection.data.ts
> [master] bookmark collection unit test 작성

- .github/workflows/cicd.yml
> npm run test시 prisma DATABASE_URL을 위해 환경변수 설정

- src/bookmarkCollection/bookmark-collection.service.spec.ts
> test code 수정

- src/admin/admin.service.ts
- src/articleReportLog/article-report-log.service.ts
> fix: admin api 수정

- src/userReportLog/user-report-log.service.ts
> fix: ban당한 유저들은 신고목록에 안뜨도록 수정

- src/admin/admin.controller.ts
- src/admin/admin.service.ts
> feat: 유저 정지 해제 api 추가

- src/article/article.service.ts
> 게시글 수정 이력 확인시 북마크 정보도 확인할 수 있도록 수정:

- .github/workflows/cicd.yml
> Update script for testing

- src/bookmark/bookmark.service.spec.ts
- src/bookmark/bookmark.service.ts
- src/bookmark/data/bookmark.data.ts
- src/bookmarkCollection/bookmark-collection.service.spec.ts
- src/bookmarkCollection/data/bookmark-collection.data.ts
> [master] feat: bookmark & bookmarkcollection unit testing

- src/bookmark/bookmark.service.spec.ts
> ADD mock resolved value

- src/bookmark/bookmark.service.spec.ts
- src/bookmark/bookmark.service.ts
> create bookmark upsert로 수정

- src/article/article.service.spec.ts
> acceptedAt 수정
